
import Footer from "@/_component/admin/Footer";
import Header from "@/_component/admin/Header";
import Sidebar from "@/_component/admin/Sidebar";
import { ToastContainer } from "react-toastify";


export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/assets/css/admin.css" />
      </head>
      <body>
        <div className="app-container app-theme-white body-tabs-shadow fixed-sidebar fixed-header">
          <Header />
          <div className="app-main">
            <Sidebar />
            <div className="app-main__outer">
              {children}
              <Footer />
            </div>
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
